### ISSUE TITLE
 Declarative option with data attributes?

### ISSUE THREAD

**Issue by fluxxus** [daveberning/griddle#4]
As the title says, besides classes to have an option of writing something like `data-grid` or just `grid` in `HTML`. That would activate grid on the selected element of course.

Honestly don't know why, but I always liked that approach :)

**Comment by daveberning** [comment]
I originally explored options like `grid="has-col-2"` and `col="is-2-md is-4-lg"` but opted out of it. In case if HTML were to introduce their own `grid` and `col` attributes. Or if projects have their own props with the same name.

The `data-grid` and `data-col` approach is good though. I'll keep this open in the meantime to gage interest. Thanks!

**Comment by fluxxus** [comment]
Ok, makes sense!
